name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v3
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash





# name: Java CI with Maven

# on: 
#  workflow_call:
#   inputs:
#     app-name:
#       description: 'Application Name'
#       required: true
#       type: string
#     java-version:
#       description: 'java version'
#       required: false
#       type: string
#       default: '17'

# jobs:
#   build_test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: test
#         run: echo hello world
#       # - name: checkout
#       #   uses: actions/checkout@v4
#       #   with:
#       #     repository: Meselu2/springapplication_demo_newman
#       #     token: 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
#       #     fetch-depth:0
#       # - name: set up JDK
#       #   uses: actions/setup-java@v3
#       #   with:
#       #     java-version: ${{ inputs.java-version}}
#       #     distribution: 'temurin'
#       #     cache: maven
#       # - name: Build with Maven
#       #   run: mvn clean install
#       # - name: Upload Github Build Artifact
#       #   uses: actions/upload-artifact@v2
#       #   with:
#       #     name: ${{input.app-name}}-build-artifact
#       #     path: build