name: common-workflow

on: 
 workflow_call:
  inputs:
    app-name:
      description: 'Application Name'
      required: true
      type: string
    java-version:
      description: 'java version'
      required: false
      type: string
      default: '17'
    run-sonar-scan:
      description: 'Sonar scan'
      required: false
      type: boolean
      default: true
    run-static-scan:
      description: 'static scan'
      required: false
      type: boolean
      default: true
    run-reload-test:
      description: 'Reload performance test'
      required: false
      type: boolean
      default: true
    reload-test-scenario:
      description: 'scenario name'
      type: string
      required: false

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: |
         echo 'hello world'
         echo ${{inputs.app-name}}
         echo ${{inputs.java-version}}
         echo ${{inputs.run-sonar-scan}}
         echo ${{inputs.run-static-scan}}
         echo ${{inputs.run-reload-test}}
         echo ${{inputs.reload-test-scenario}}
         

      # - name: set up JDK
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: ${{ inputs.java-version}}
      #     distribution: 'temurin'
      #     cache: maven
      # - name: Build with Maven
      #   run: mvn clean install
      # - name: maven build
      #   uses: ./.github/workflows/build-test.yml
        # with:
        #   repository: Meselu2/springapplication_demo_newman
        #   repo-token: ${{ secrets.REPO_TOKEN}}
